config/routes.rb
Spinka::Application.routes.draw do

  root      'static_pages#home'

  resources :users, path: '/uzytkownicy', path_names: { edit: 'edycja' }
  get       '/rejestracja'            => 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  get       '/logowanie'              => 'sessions#new'
  delete    '/wyloguj'                => 'sessions#destroy'

  resources :news, path: '/newsy', path_names: { new: 'nowy', edit: 'edycja' }

  resources :comments, path:'/komentarze', only: [:create, :edit, :update, :destroy], path_names: { edit: 'edycja-komentarza' }

  resources :forum_layouts, only: [:create, :update]

  shallow do
    scope shallow_path: 'forum' do
      resources :categories, path: 'kategorie', only: [ :new, :create, :edit, :update, :show, :destroy ], path_names: { new: 'nowa', edit: 'edycja' } do
        resources :topics, path: 'tematy', only: [ :new, :create, :edit, :update, :show, :destroy ], path_names: { new: 'nowy', edit: 'edycja' } do
          resources :posts, path: 'odpowiedzi', only: [:create, :edit, :update, :destroy], path_names: { edit: 'edycja' }
        end
      end
    end
  end

  get 'forum/kategorie' => 'categories#index'

  get       '/onas'                   => 'static_pages#onas'
  get       '/pomoc'                  => 'static_pages#pomoc'
  get       '/kontakt'                => 'static_pages#kontakt'
  get       '/forum'                  => 'static_pages#forum'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { email.downcase! }
	before_create :create_remember_token

	has_many :news
	has_many :forum_layouts, dependent: :destroy
	has_many :comments
	has_many :topics
	has_many :posts
	has_many :last_readed_posts, dependent: :destroy

	has_secure_password
	validates :password, length: { minimum: 6}, on: :create

	VALID_USERNAME = /\A[\w\dęóąśłżźćń]+( ?[\w\dęóąśłżźćń]+)*\z/i

	validates :username, presence: true, length: { maximum: 25 },format: { with: VALID_USERNAME }, uniqueness: { case_sensitive: false }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	def to_param
    "#{username}"
  end

	private

	def create_remember_token
		self.remember_token = User.encrypt(User.new_remember_token)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:edit, :update, :index]
	before_action :correct_user, only: [:edit, :update]
	before_action :admin_user, only: [:destroy]
	before_action :not_signed_in?, only: [:new, :create]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Pomyslnie zarejestrowany"
			redirect_to @user
		else
			render 'new'
		end
	end

	def show
		@user = User.where('lower(username) = ?', params[:id].downcase).first
	end

	def index
		@users = User.paginate(page: params[:page])
	end

	def edit
		@user = User.where('lower(username) = ?', params[:id].downcase).first
	end

	def update
		@user = User.where('lower(username) = ?', params[:id].downcase).first
		user_params.delete(["password", "password_confirmation"])
		if @user.update_attributes(user_params)
			flash[:success] = "Profil zaktualizowany"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.where('lower(username) = ?', params[:id].downcase).first.destroy
		flash[:success] = "użytkonik usunięty."
		redirect_to users_url
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :moderator, :editor)
	end

	def not_signed_in?
		redirect_to root_url, notice: "Jestes już zalogowany" unless current_user.nil?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_order_link.html.erb
<% if params[:order] == ordering && params[:asc] == 'ASC' %>
<%= link_to "<span class='small glyphicon glyphicon-sort'></span> #{label}".html_safe, users_path(order: ordering, asc: 'DESC', page: params[:page]) %>
<% else %>
<%= link_to "<span class='small glyphicon glyphicon-sort'></span> #{label}".html_safe, users_path(order: ordering, asc: 'ASC', page: params[:page]) %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "#{@user.username} - Edycja") %>

<div class="row">
	<div class="col-md-12">
		<%= render 'shared/error_messages', object: @user %>
	</div>
</div>

<h3><strong><%= @user.username %></strong> > <small>Edycja profilu</small></h3>
<br>
<div class='col-md-6'>
	<%= form_for @user, html: { class: "form-horizontal" } do |f| %>

	<div class="form-group">
		<%= f.label :first_name, "imie", class: "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_field :first_name, class: "form-control", placeholder: @user.first_name %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :last_name, "nazwisko", class: "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_field :last_name, class: "form-control" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :email, "email", class: "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_field :email, class: "form-control", text: @user.email %>
		</div>
	</div>
	<% if current_user && current_user.admin? %>
	<div class="checkbox">
		<%= f.label :moderator, "moderator" %>
		<%= f.check_box :moderator %>
	</div>
	<div class="checkbox">
		<%= f.label :editor, "redaktor" %>
		<%= f.check_box :editor %>
	</div>
	<% end %>

	<div class="col-md-offset-4">
		<%= f.submit "aktualizuj", class: "btn btn-large btn-primary" %>
	</div>

	<% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, "Użytkownicy") %>

<h3>Użytkownicy:</h3>

<%= pagination_links(@users) %>

<table class="table table-hover">
	<thead>
		<tr>
			<th>
				<%= render 'users/order_link', ordering: 'username', label: 'Login' %>
			</th>
			<th>
				<%= render 'users/order_link', ordering: 'email', label: 'Email' %>
			</th>
			<th>
				<%= render 'users/order_link', ordering: 'first_name', label: 'Imie' %>
			</th>
			<th>
				<%= render 'users/order_link', ordering: 'last_name', label: 'Nazwisko' %>
			</th>
			<th>Funkcje</th>
			<% if current_user && current_user.admin? %>
			<th class="col-md-1"></th>
			<th class="col-md-1"></th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% @users.order("#{params[:order]} #{params[:asc]}").each do |user| %>
		<tr>
			<td><%= link_to user.username, user_path(user) %></td>
			<td><%= user.email %></td>
			<td><%= user.first_name %></td>
			<td><%= user.last_name %></td>
			<td><%= 'Administrator' if user.admin == true %> <%= 'Moderator' if user.moderator == true %> <%= 'Redaktor' if user.editor == true %></td>
			<% if current_user && current_user.admin? %>
			<td>
				<%= link_to "<span class='glyphicon glyphicon-pencil'></span> edytuj".html_safe, edit_user_path(user), class: "btn btn-default btn-sm" %>
			</td>
			<td>
				<% if !current_user?(user) %>
				<%= render 'shared/delete_link', object: user %>
				<% end %>
			</td>
			<% end %>
		</tr>
		<% end %>
	</tbody>
</table>

<%= pagination_links(@users) %>

app/views/users/new.html.erb
<% provide(:title, "Rejestracja") %>

<div class="row">
	<div class="col-md-12">
		<%= render 'shared/error_messages', object: @user %>
	</div>
</div>
<h3>Rejestracja</h3>

<div class="col-md-6">
	<%= form_for @user, html: { class: "form-horizontal" } do |f| %>

	<div class="form-group">
		<%= f.label :username, "login", class: "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_field :username, class: "form-control" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :email, "email", class: "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.text_field :email, class: "form-control" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :password, "hasło", class: "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.password_field :password, class: "form-control" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :password_confirmation, "potwierdź hasło", class: "col-sm-4 control-label" %>
		<div class="col-sm-8">
			<%= f.password_field :password_confirmation, class: "form-control" %>
		</div>
	</div>

	<div class="col-md-offset-4">
		<%= f.submit "stwórz", class: "btn btn-large btn-primary" %>
		<h5>Posiadasz już konto? Zaloguj się <%= link_to "tutaj", logowanie_path %></h5>
	</div>
	<% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<h3><%= @user.username %></h3>

<div class="row">
	<div class="col-md-3">
	<%= @user.first_name %> <%= @user.last_name %>
	<br>
	email: <%= @user.email %>
	<% if administrator or owner(@user.id) %>
	<hr>
	<div class="btn btn-sm btn-primary"><%= link_to "Edycja", edit_user_path(@user) %></div>
	<% end %>
	</div>
</div>