config/routes.rb
Spinka::Application.routes.draw do

  root      'static_pages#home'

  resources :users, path: '/uzytkownicy', path_names: { edit: 'edycja' }
  get       '/rejestracja'            => 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  get       '/logowanie'              => 'sessions#new'
  delete    '/wyloguj'                => 'sessions#destroy'

  resources :news, path: '/newsy', path_names: { new: 'nowy', edit: 'edycja' }

  resources :comments, path:'/komentarze', only: [:create, :edit, :update, :destroy], path_names: { edit: 'edycja-komentarza' }

  resources :forum_layouts, only: [:create, :update]

  shallow do
    scope shallow_path: 'forum' do
      resources :categories, path: 'kategorie', only: [ :new, :create, :edit, :update, :show, :destroy ], path_names: { new: 'nowa', edit: 'edycja' } do
        resources :topics, path: 'tematy', only: [ :new, :create, :edit, :update, :show, :destroy ], path_names: { new: 'nowy', edit: 'edycja' } do
          resources :posts, path: 'odpowiedzi', only: [:create, :edit, :update, :destroy], path_names: { edit: 'edycja' }
        end
      end
    end
  end

  get 'forum/kategorie' => 'categories#index'

  get       '/onas'                   => 'static_pages#onas'
  get       '/pomoc'                  => 'static_pages#pomoc'
  get       '/kontakt'                => 'static_pages#kontakt'
  get       '/forum'                  => 'static_pages#forum'

end

app/models/news.rb
class News < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	default_scope -> { order('created_at DESC') }
	validates :title, presence: true
	validates :user_id, presence: true
	validates :content, presence: true
	validates :teaser, presence: true, length: { maximum: 250 }
	def to_param
		"#{id}-#{title.parameterize}"
	end

	def short_title(len)
		if title.length > len
			"#{title.first(len)}&#8230;"
		else
			title
		end
	end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
before_action :signed_in_user, only: [ :new, :create, :edit, :update, :destroy]
before_action :editor_user, only: [:new, :create, :edit, :update, :destroy]


  def new
    @news = News.new
  end

  def create
    @news = current_user.news.build(news_params)
    if @news.save
      redirect_to @news
    else
      render 'new'
    end
  end

  def show
    if News.find_by_id(params[:id])
      @news = News.find_by_id(params[:id])
      @comments = @news.comments
    else
      redirect_to root_url
    end
  end

  def edit
    if News.find_by_id(params[:id])
      @news = News.find_by_id(params[:id])
    else
      redirect_to root_url
    end
  end

  def update
    @news = News.find_by_id(params[:id])

    if @news.update_attributes(news_params)
      flash[:success] = "Artykuł zaktualizowany"
      redirect_to @news
    else
      render 'edit'
    end
  end

  def index
    @news = News.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    News.find(params[:id]).destroy
    flash[:success] = "Artykuł usunięty."
    redirect_to news_url
  end

  private

  def news_params
    params.require(:news).permit(:title, :teaser, :content)
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_bottom_buttons.html.erb
<div class="bottom-buttons">
	<a href="#top" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-arrow-up"></span> na górę</a>
	<% if owner(@news.user.id) || editor %>
	<%= link_to "<span class='glyphicon glyphicon-pencil'></span> edytuj".html_safe, edit_news_path(@news), class: "btn btn-default btn-sm" %>
	<% if administrator %>
	<%= render 'shared/delete_link', object: @news %>
	<% end %>
	<% end %>
</div>

app/views/news/_news.html.erb
<div class="news">
	<div class="row heading">
		<div class= "col-md-8 panel-title">
			<%= link_to news.title, news_path(news) %>
		</div>
		<small class="col-md-4 text-muted">
			<%= l(news.created_at, format: :long) %>
		</small>
	</div>
	<div class="body">
		<%= link_to news.teaser, news_path(news) %>
	</div>
	<div class="footer">
		<%= link_to "komentarze (#{news.comments.count})", news_path(news, anchor: "news-comments") %>
		<% if administrator %>
		<div class= "pull-right">
			<%= link_to "<span class='glyphicon glyphicon-pencil'></span> edytuj".html_safe, edit_news_path(news), class: "btn btn-default btn-sm" %>
			<%= render 'shared/delete_link', object: news %>
		</div>
		<% end %>
	</div>
</div>

app/views/news/edit.html.erb
<%= provide(:title, "#{@news.title} - edycja") %>
<%= render 'shared/error_messages', object: @news %>
<h3><%= @news.title %></h3>

<%= form_for @news, html: { class: "form" } do |f| %>

<div class="form-group">	
	<%= f.label :title, "Tytuł" %>
	<%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :teaser, "Zajawka (max 250 znaków)" %>
	<%= f.text_area :teaser, class: "form-control", rows: 5 %>
</div>

<div class="form-group">
	<%= f.label :content, "Treść artykułu" %>
	<%= f.text_area :content, class: "form-control", rows: 15 %>
</div>

<br>

<%= f.submit "Aktualizuj", class: "btn btn-primary" %>

<% end %>

app/views/news/index.html.erb
<% provide(:title, "Aktualności") %>

<section class="col-md-9">
	<h3>Aktualności:</h3>
	<% if editor %>
	<%= link_to "<span class='glyphicon glyphicon-plus'></span> dodaj nowy".html_safe, new_news_path, class: "btn btn-default btn-sm" %>
	<br>
	<% end %>
	<br>

<%= render @news %>

	<%= pagination_links(@news) %>
</section>
<aside class="col-md-3">
	<%= render 'static_pages/sidebar' %>
</aside>

app/views/news/new.html.erb
<% provide(:title, "Nowy news") %>

<div class="row">
	<div class="col-md-12">
		<%= render 'shared/error_messages', object: @news %>
	</div>
</div>
<%= form_for @news, html: { class: "form" } do |f| %>

<div class="form-group">
	<%= f.label :title, "Tytuł" %>
	<%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :teaser, "Zajawka (max 250 znaków)" %>
	<%= f.text_area :teaser, class: "form-control", rows: 5 %>
</div>

<div class="form-group">
	<%= f.label :content, "Treść artykułu" %>
<%= f.text_area :content, class: "form-control", rows: 15 %>
</div>

<br>

<%= f.submit "Dodaj", class: "btn btn-primary" %>

<% end %>

app/views/news/show.html.erb
<%= provide(:title, @news.title) %>

<section class="col-md-9">

	<h3 id="top"><%= @news.title %></h3>
	<div class="row text-muted small">
		<div class="col-md-6 ">
			Dodane przez: <%= @news.user.username %> | <%= link_to "Komentarze: #{@comments.count}", anchor: "news-comments" %>
		</div>
		<div class="col-md-6">
			<div class="pull-right"><%= l(@news.created_at.to_datetime, format: :long) %></div>
		</div>
	</div>

	<section id="news-content">

		<%= simple_format(@news.content, {}, sanitize: false) %>
		<%= render 'bottom_buttons' %>

	</section>

	<section id="news-comments">

		<% if @comments.any? %>
		<h4>Komentarze (<%= @comments.count %>)</h4>
		<hr>
		<%= render @comments %>
		<a href="#top" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-arrow-up"></span> na górę</a>
		<% else %>
		<h4>Artykuł nie został jeszcze skomentowany, bądź pierwszy</h4>
		<% end %>

	</section>
	<br>
	<section id="news-comments-add">
		<% if current_user %>
		<%= render 'comments/comment_form' %>
		<% else %>
		<h4 class="text-muted">Aby skomentować artykuł musisz być zalogowany</h4>
		<% end %>
	</section>
</section>

<aside class="col-md-3">
	<%= render 'static_pages/sidebar' %>
</aside>