config/routes.rb
Spinka::Application.routes.draw do

  root      'static_pages#home'

  resources :users, path: '/uzytkownicy', path_names: { edit: 'edycja' }
  get       '/rejestracja'            => 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  get       '/logowanie'              => 'sessions#new'
  delete    '/wyloguj'                => 'sessions#destroy'

  resources :news, path: '/newsy', path_names: { new: 'nowy', edit: 'edycja' }

  resources :comments, path:'/komentarze', only: [:create, :edit, :update, :destroy], path_names: { edit: 'edycja-komentarza' }

  resources :forum_layouts, only: [:create, :update]

  shallow do
    scope shallow_path: 'forum' do
      resources :categories, path: 'kategorie', only: [ :new, :create, :edit, :update, :show, :destroy ], path_names: { new: 'nowa', edit: 'edycja' } do
        resources :topics, path: 'tematy', only: [ :new, :create, :edit, :update, :show, :destroy ], path_names: { new: 'nowy', edit: 'edycja' } do
          resources :posts, path: 'odpowiedzi', only: [:create, :edit, :update, :destroy], path_names: { edit: 'edycja' }
        end
      end
    end
  end

  get 'forum/kategorie' => 'categories#index'

  get       '/onas'                   => 'static_pages#onas'
  get       '/pomoc'                  => 'static_pages#pomoc'
  get       '/kontakt'                => 'static_pages#kontakt'
  get       '/forum'                  => 'static_pages#forum'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :topics
	has_many :forum_layouts, dependent: :destroy
	def to_param
		"#{id}-#{title.parameterize}"
	end

	def collapsed?(user)
		if forum_layouts.find_by_user_id(user.id)
			forum_layouts.find_by_user_id(user.id).collapsed
		else
			false
		end
	end

	def collapse!(user)
		if forum_layouts.find_by_user_id(user.id)
			@layout = forum_layouts.find_by_user_id(user.id)
			@layout.collapsed = 1
			@layout.save
		else
			forum_layouts.create!(user_id: user.id, collapsed: true)
		end
	end

	def uncollapse!(user)
		@layout = forum_layouts.find_by_user_id(user.id)
		@layout.collapsed = 0
		@layout.save
	end

	def slide_up!(user_id: "")
		unless user_id.blank?
			unless self.forum_layouts.find_by(user_id: user_id) == ForumLayout.where("user_id == ?", user_id).order("user_custom_index ASC").first
				@self_layout = self.forum_layouts.find_by(user_id: user_id)
				@category_up = ForumLayout.where("user_id == ? AND user_custom_index < ?", user_id, self.forum_layouts.find_by(user_id: user_id).user_custom_index).order("user_custom_index ASC").last
				@swap = @self_layout.user_custom_index
				@self_layout.user_custom_index = @category_up.user_custom_index
				@category_up.user_custom_index = @swap
				@category_up.save
				@self_layout.save
			end
		else
			unless self == Category.all.order(:custom_index).first
				@category_up = Category.where("custom_index < ?", self.custom_index).order("custom_index ASC").last
				@swap = self.custom_index
				self.custom_index = @category_up.custom_index
				@category_up.custom_index = @swap
				@category_up.save
				self.save
			end
		end
	end

	def slide_down!(user_id: "")
		unless user_id.blank?
			unless self.forum_layouts.find_by(user_id: user_id) == ForumLayout.where("user_id == ?", user_id).order("user_custom_index ASC").last
				@self_layout = self.forum_layouts.find_by(user_id: user_id)
				@category_down = ForumLayout.where("user_id == ? AND user_custom_index > ?", user_id, self.forum_layouts.find_by(user_id: user_id).user_custom_index).order("user_custom_index ASC").first
				@swap = self.forum_layouts.find_by(user_id: user_id).user_custom_index
				@swap = @self_layout.user_custom_index
				@self_layout.user_custom_index = @category_down.user_custom_index
				@category_down.user_custom_index = @swap
				@category_down.save
				@self_layout.save
			end		else
			unless self == Category.all.order(:custom_index).last
				@category_down = Category.where("custom_index > ?", self.custom_index).order("custom_index ASC").first
				@swap = self.custom_index
				self.custom_index = @category_down.custom_index
				@category_down.custom_index = @swap
				@category_down.save
				self.save
			end
		end
	end

	validates :title, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :signed_in_user, only: [:index, :new, :create, :edit, :update, :destroy]
	before_action :admin_user, only: [:index, :new, :create, :edit, :update, :destroy]

	def show
		@category = Category.find_by_id(params[:id])
		@topics = @category.topics.paginate(page: params[:page])
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.create(category_params)
		if @category.save
			redirect_to forum_kategorie_path
		else
			render 'new'
		end
	end

	def edit
		@category = Category.find_by(id: params[:id])
	end

	def update
		if params[:category][:change_type] == "position"
			@category = Category.find_by(id: params[:category][:id])
			if params[:category][:dir] == "up"
				@category.slide_up!
			elsif params[:category][:dir] == "down"
				@category.slide_down!
			end
			redirect_to :back
		elsif params[:category][:change_type] == "title"
			@category = Category.find_by(id: params[:id])
			@category.update_attributes(category_params)
			if @category.save
				flash[:success] = "Nazwa zaktualizowana"
				redirect_to @category
			else
				render 'edit'
			end
		end
	end

	def destroy
		Category.find_by_id(params[:id]).delete
		redirect_to :back
	end

	def index
		@categories = Category.all.order(:custom_index)
	end

	private

	def category_params
		params.require(:category).permit(:title)
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="panel panel-default table-responsive">
	<%= render 'categories/category_header', category: category %>
	<div id="<%= category.title.split(" ").join("-") %>" class="collapse <%= 'in' unless category.forum_layouts.find_by(user_id: current_user).try(:collapsed) == true %>">
		<% if category.topics.any? %>
		<table class="table table-hover">
			<thead>
				<tr>
					<th class="col-md-6"><small>Temat</small></th>
					<th class="col-md-2 centered"><small>Data założenia</small></th>
					<th class="col-md-2 centered"><small>Ilość odpowiedzi</small></th>
					<th class="col-md-2 centered"><small>Ostatnia odpowiedź</small></th>
				</tr>
			</thead>
			<tbody>
				<% category.topics.first(10).each do |topic| %>
				<tr>
					<td>
						<% if current_user && topic.readed?(current_user) %>
						<%= render 'topics/first_new_post_link', object: topic %>
						<% end %>
						<%= link_to render('topics/title', object: topic.title) , topic %>
					</td>
					<td class="centered">
						<small>
							<%= l(topic.created_at, format: :short) %>
						</small>
					</td>
					<td class="centered">
						<small>
							<%= topic.post_count%>
							<% if current_user && topic.readed?(current_user) %>
							<%= " (+#{topic.new_posts(current_user)})" %>
							<% end %>
						</small>
					</td>
					<td class="centered">
						<small>
							<% if topic.last_post.blank? %>
							-
							<% else %>
							<%= "#{time_ago_in_words(topic.last_post)} temu" %>
							<% end %>
						</small>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<% else %>
		<div class="panel-body">
			<h5 class="text-muted">Nie ma tu niczego</h5>
		</div>
		<% end %>
	</div>
</div>

app/views/categories/_category_header.html.erb
<div class="panel-heading">
	<b><%= link_to category.title, category %></b>
	<% if current_user %>
	<div class="dropdown pull-right">
		<a href="#" class="dropdown-toggle btn btn-xs btn-default" data-toggle="dropdown">
			<span class="glyphicon glyphicon-chevron-down"></span>
		</a>
		<ul class="dropdown-menu">
			<li><a id="collapse_form-<%= category.id %>">
				<%= render 'categories/collapse_form', object: category.id %>
				</a>
			</li>
			<li><a href="#">Liczba postów</a></li>
			<li><a>
				<%= render 'categories/user_slider', cat: category.id %>
			</a></li>
		</ul>
	</div>
	<% end %>
</div>

app/views/categories/_collapse.html.erb
<% if current_user.forum_layouts.find_by(category_id: cat) %>
	<%= form_for(current_user.forum_layouts.find_by(category_id: cat), remote: true) do |f| %>
		<%= f.hidden_field :change_type, value: "collapse" %>
		<%= f.button(type: "submit", id: "collapse-#{cat}", class: "collapse-button") do %>
			<span class="glyphicon glyphicon-chevron-up small"></span> Zwiń
		<% end %>
	<% end %>
<% else %>
	<%= form_for(current_user.forum_layouts.build(category_id: cat), remote: true) do |f| %>
		<%= f.hidden_field :category_id, value: cat %>
		<%= f.hidden_field :change_type, value: "collapse" %>
		<%= f.button(type: "submit", id: "collapse-#{cat}", class: "collapse-button") do %>
			<span class="glyphicon glyphicon-chevron-up small"></span> Zwiń
		<% end %>
	<% end %>
<% end %>

app/views/categories/_collapse_form.html.erb
<% if Category.find_by_id(object).collapsed?(current_user) %>
	<%= render 'categories/uncollapse', cat: object %>
<% else %>
	<%= render 'categories/collapse', cat: object %>
<% end %>

app/views/categories/_slider.html.erb
<div>
<% unless cat == Category.order(:custom_index).first %>
	<%= form_for(cat) do |f| %>
		<%= f.hidden_field :id, value: cat.id %>
		<%= f.hidden_field :dir, value: 'up' %>
		<%= f.hidden_field :change_type, value: 'position' %>
		<%= f.button(type: "submit", class: "btn btn-xs btn-default slider-btn") do %>
			<span class="glyphicon glyphicon-chevron-up slider"></span>
		<% end %>
	<% end %>
<% end %>
<% unless cat == Category.order(:custom_index).last %>
	<%= form_for(cat) do |f| %>
		<%= f.hidden_field :id, value: cat.id %>
		<%= f.hidden_field :dir, value: 'down' %>
		<%= f.hidden_field :change_type, value: 'position' %>
		<%= f.button(type: "submit", class: "btn btn-xs btn-default slider-btn") do %>
			<span class="glyphicon glyphicon-chevron-down slider"></span>
		<% end %>
	<% end %>
<% end %>
</div>

app/views/categories/_uncollapse.html.erb
<%= form_for(current_user.forum_layouts.find_by_category_id(cat), remote: true) do |f| %>
	<%= f.hidden_field :change_type, value: "collapse" %>
	<%= f.button(type: "submit", id: "uncollapse-#{cat}", class: "collapse-button") do %>
		<span class="glyphicon glyphicon-chevron-down small"></span> Rozwiń
	<% end %>
<% end %>

app/views/categories/_user_slider.html.erb
<div class="center-block">
<ul class="list-inline">
<li>
<% if current_user.forum_layouts.find_by(category_id: cat) %>
	<% unless current_user.forum_layouts.find_by(category_id: cat) == current_user.forum_layouts.order("user_custom_index ASC").first %>
		<%= form_for(current_user.forum_layouts.find_by(category_id: cat)) do |f| %>
			<%= f.hidden_field :dir, value: 'up' %>
			<%= f.hidden_field :category_id, value: cat %>
			<%= f.hidden_field :user_id, value: current_user.id %>
			<%= f.hidden_field :change_type, value: 'position' %>
			<%= f.button(type: "submit", class: "btn btn-xs btn-default slider-btn") do %>
				W górę <span class="glyphicon glyphicon-chevron-up slider"></span>
			<% end %>
		<% end %>
	<% end %>
<% else %>
	<% unless Category.find_by(id: cat) == Category.all.order("custom_index ASC").first %>
		<%= form_for(current_user.forum_layouts.build(category_id: cat)) do |f| %>
			<%= f.hidden_field :dir, value: 'up' %>
			<%= f.hidden_field :category_id, value: cat %>
			<%= f.hidden_field :user_id, value: current_user.id %>
			<%= f.hidden_field :change_type, value: 'position' %>
			<%= f.button(type: "submit", class: "btn btn-xs btn-default slider-btn") do %>
				W górę <span class="glyphicon glyphicon-chevron-up slider"></span>
			<% end %>
		<% end %>
	<% end %>
<% end %>
</li>
<li>
<% if current_user.forum_layouts.find_by(category_id: cat) %>
	<% unless current_user.forum_layouts.find_by(category_id: cat) == current_user.forum_layouts.order("user_custom_index ASC").last %>
		<%= form_for(current_user.forum_layouts.find_by(category_id: cat)) do |f| %>
			<%= f.hidden_field :dir, value: 'down' %>
			<%= f.hidden_field :category_id, value: cat %>
			<%= f.hidden_field :user_id, value: current_user.id %>
			<%= f.hidden_field :change_type, value: 'position' %>
			<%= f.button(type: "submit", class: "btn btn-xs btn-default slider-btn") do %>
				<span class="glyphicon glyphicon-chevron-down slider"></span> W dół
			<% end %>
		<% end %>
	<% end %>
<% else %>
	<% unless Category.find_by(id: cat) == Category.all.order("custom_index ASC").last %>
		<%= form_for(current_user.forum_layouts.build(category_id: cat)) do |f| %>
			<%= f.hidden_field :dir, value: 'down' %>
			<%= f.hidden_field :category_id, value: cat %>
			<%= f.hidden_field :user_id, value: current_user.id %>
			<%= f.hidden_field :change_type, value: 'position' %>
			<%= f.button(type: "submit", class: "btn btn-xs btn-default slider-btn") do %>
				<span class="glyphicon glyphicon-chevron-down slider"></span> W dół
			<% end %>
		<% end %>
	<% end %>
<% end %>
</li>
</ul>
</div>

app/views/categories/edit.html.erb
<% provide(:title, "#{@category.title} - Edycja") %>

<%= render 'shared/error_messages', object: @category %>
<h3><%= @category.title %></h3>

<%= form_for @category, html: { class: "form col-md-5" } do |f| %>

<div class="form-group">
	<%= f.label :title, "Tytuł" %>
	<%= f.text_field :title, class: "form-control" %>
	<%= f.hidden_field :change_type, value: 'title' %>
	<br>
	<%= f.submit "Aktualizuj", class: "btn btn-primary" %>
</div>

<% end %>

app/views/categories/index.html.erb
<% provide(:title, "Kategorie") %>

<h3>Kategorie</h3>
<br>
<%= link_to "<span class='glyphicon glyphicon-file'></span> nowa kategoria".html_safe, new_category_path, class: "btn btn-primary btn-xs" %>
<br>
<br>
<div class="table-responsive">
	<table class="table table-hover category-table">
		<thead>
			<tr>
				<th></th>
				<th>Nazwa</th>
				<th>Tematy</th>
				<th>Posty</th>
				<th class="col-sm-1"></th>
				<th class="col-sm-1"></th>
			</tr>
		</thead>
		<tbody>
			<% @categories.each do |category| %>
			<tr>
				<td>
					<%= render 'categories/slider', cat: category %>
				</td>
				<td>
					<p>
						<%= link_to category.title, category %>
					</p>
				</td>
				<td>
					<%= category.topics.count %>
				</td>
				<td>
					<% category.topics.each{ |topic| @post_sum ? @post_sum += topic.post_count : @post_sum = 0 } %>
					<%= @post_sum + @post_sum = 0 %>
				</td>
				<td>
					<%= link_to "<span class='glyphicon glyphicon-pencil'></span> edytuj".html_safe, edit_category_path(category), class: "btn btn-default btn-sm" %>
				</td>
				<td>
					<%= render 'shared/delete_link', object: category %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/categories/new.html.erb
<% provide(:title, "Nowa kategoria") %>

<h3>Nowa kategoria</h3>
<br>
<div class="row">
	<div class="col-md-12">
		<%= render 'shared/error_messages', object: @category %>
	</div>
</div>
<br>
<%= form_for @category, html: { class: "form" } do |f| %>

<div class="form-group col-md-6">
	<%= f.label :title, "Tytuł" %>
	<%= f.text_field :title, class: "form-control" %>
</div>
<div class="col-md-7">
<%= f.submit "Dodaj", class: "btn btn-primary" %>
</div>
<% end %>

app/views/categories/show.html.erb
<% provide(:title, @category.title) %>

<h3><%= @category.title %> <%= link_to "<span class='glyphicon glyphicon-pencil'></span> Edycja".html_safe, edit_category_path(@category), class: "btn btn-default btn-xs" if current_user && current_user.admin? %></h3>
<br>
<% if current_user %>
<%= link_to "<span class='glyphicon glyphicon-file'></span> nowy temat".html_safe, new_category_topic_path(category_id: @category.id), class: "btn btn-primary btn-xs" %>
<br>
<br>
<% end %>
<% if @topics.any? %>
<table class="table table-hover">
	<thead>
		<tr>
			<th class="col-md-6"><small>Temat</small></th>
			<th class="centered"><small>Data założenia</small></th>
			<th class="centered"><small>Ilość odpowiedzi</small></th>
			<th class="centered"><small>Ostatnia odpowiedź</small></th>
		</tr>
	</thead>
	<tbody>
		<% @topics.each do |topic| %>
		<tr>
			<td>
				<% if current_user && topic.readed?(current_user) %>
				<%= render 'topics/first_new_post_link', object: topic %>
				<% end %>
				<%= link_to render('topics/title', object: topic.title) , topic %>
			</td>
			<td class="centered">
				<%= l(topic.created_at, format: :short) %>
			</td>
			<td class="centered">
				<%= topic.post_count%>
				<% if current_user && topic.readed?(current_user) %>
				<%= " (+#{topic.new_posts(current_user)})" %>
				<% end %>
			</td>
			<td class="centered">
				<% if topic.last_post.blank? %>
				-
				<% else %>
				<%= "#{time_ago_in_words(topic.last_post)} temu" %>
				<% end %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= pagination_links(@topics) %>
<% else %>
<br>
<br>
<h4>Nie ma tu niczego</h4>
<% end %>