config/routes.rb
Spinka::Application.routes.draw do

  root      'static_pages#home'

  resources :users, path: '/uzytkownicy', path_names: { edit: 'edycja' }
  get       '/rejestracja'            => 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  get       '/logowanie'              => 'sessions#new'
  delete    '/wyloguj'                => 'sessions#destroy'

  resources :news, path: '/newsy', path_names: { new: 'nowy', edit: 'edycja' }

  resources :comments, path:'/komentarze', only: [:create, :edit, :update, :destroy], path_names: { edit: 'edycja-komentarza' }

  resources :forum_layouts, only: [:create, :update]

  shallow do
    scope shallow_path: 'forum' do
      resources :categories, path: 'kategorie', only: [ :new, :create, :edit, :update, :show, :destroy ], path_names: { new: 'nowa', edit: 'edycja' } do
        resources :topics, path: 'tematy', only: [ :new, :create, :edit, :update, :show, :destroy ], path_names: { new: 'nowy', edit: 'edycja' } do
          resources :posts, path: 'odpowiedzi', only: [:create, :edit, :update, :destroy], path_names: { edit: 'edycja' }
        end
      end
    end
  end

  get 'forum/kategorie' => 'categories#index'

  get       '/onas'                   => 'static_pages#onas'
  get       '/pomoc'                  => 'static_pages#pomoc'
  get       '/kontakt'                => 'static_pages#kontakt'
  get       '/forum'                  => 'static_pages#forum'

end

app/views/layouts/_admin_menu.html.erb
<li>
<%= link_to 'Kategorie', forum_kategorie_path %>
</li>

app/views/layouts/_breadcrumbs.html.erb
<% @current_path = request.original_url %>
<% if @current_path.match('forum') && !@current_path.split('/').last.match('forum') %>
<small>
	<ol class="breadcrumb">
		<li><%= link_to "Forum", forum_url %></li>
		<% if @current_path.include?('/odpowiedzi/') %>
			<% @po = Post.find_by_id(params[:id]) %>
			<li><%= link_to @po.topic.category.title, category_path(@po.topic.category) %></li>
			<li><%= link_to @po.topic.title, topic_path(@po.topic) %></li>
			<% if @current_path.match(/edycja\z/) %>
				<li class="active">Edycja odpowiedzi</li>
			<% else %>
				<li class="active"><%= @po.id %></li>
			<% end %>
		<% elsif @current_path.include?('/tematy/') %>
			<% if @current_path.match(/nowy\z/) %>
				<% @cat = Category.find_by_id(params[:category_id]) %>
				<li><%= link_to @cat.title, category_path(@cat) %></li>
				<li class="active">Nowy temat</li>
			<% elsif @current_path.match(/edycja\z/) %>
				<% @top = Topic.find_by_id(params[:id]) %>
				<li><%= link_to @top.category.title, category_path(@top.category) %></li>
				<li><%= link_to @top.title, topic_path(@top) %></li>
				<li class="active">Edycja</li>
			<% else %>
				<% @top = Topic.find_by_id(params[:id]) %>
				<li><%= link_to @top.category.title, category_path(@top.category) %></li>
				<li><%= @top.title %></li>
			<% end %>
		<% elsif @current_path.include?('/kategorie/') %>
			<% @cat = Category.find_by_id(params[:id]) %>
			<li class="active"><%= @cat.title %></li>
		<% end %>
	</ol>
</small>
<% end %>

app/views/layouts/_flash.html.erb
<div class="row">
	<div class="col-md-12">
		<% flash.each do |name, msg| -%>
		<%= content_tag :div, msg, class: "alert alert-#{ notice ? "info" : name}" %>
		<% end -%>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="container">
	<hr>
	<p class="col-md-10 col-md-offset-1">
		SPiNKa - Stowarzyszenie Pomocy Niepełnosprawnym Kierowcom
	</p>
</footer>

app/views/layouts/_header.html.erb
<header class="container" id="top">
<!-- 	<div class="page-header">
		<div class="row">
			<div class="col-md-2 col-sm-3 hidden-xs">
				<%= link_to image_tag('logo-transparent.png', alt: 'SPiNKa', class: 'img-responsive'), root_path %>
			</div>
			<h3 class="col-md-5 col-sm-6 col-xs-8">
				Stowarzyszenie Pomocy Niepełnosprawnym Kierowcom
				</h3>
			</div>
		</div> -->
	<div class="row">
		<div class="navbar navbar-default col-md-12">
			<div class="navbar-header col-md-2">
				<button class="btn btn-md navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="glyphicon glyphicon-chevron-down"></span>
				</button>
				<%= link_to "SPiNKa", root_path, class: 'navbar-brand' %>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li class="nav">
						<%= link_to 'Poznaj nas',	onas_path %>
					</li>
					<li>
					<%= link_to 'Aktualności', news_index_path %>
					</li>
					<li class="nav">
						<%= link_to 'Forum', forum_path %>
					</li>
					<li class="nav">
						<%= link_to 'Pomoc', pomoc_path %>
					</li>
					<li class="nav">
						<%= link_to 'Kontakt', kontakt_path %>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<% if signed_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<%= current_user.username %> <span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to 'Profil', user_path(current_user) %>
							</li>
							<li>
								<%= link_to 'Użytkownicy', users_path %>
							</li>
							<% if current_user.admin? %>
							<%= render 'layouts/admin_menu' %>
							<% end %>
							<li class="divider"></li>
							<li>
								<%= link_to 'Wyloguj', wyloguj_path, method: "delete"%>
							</li>
						</ul>
					</li>
					<% else %>
					<li class="nav">
						<%= link_to 'Zarejestruj się', rejestracja_path %>
					</li>
					<li class="nav">
						<%= link_to 'Zaloguj', logowanie_path %>
					</li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
	<%= render 'layouts/breadcrumbs' %>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>

	<section class="container">
		<%= render'layouts/flash' %>
		<%= yield %>
	</section>

	<%= render 'layouts/footer' %>
</body>
</html>